
variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-teracy-dev}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-teracy-dev}
  node_domain_affix: ${NODE_DOMAIN_AFFIX:-local}
  home_sync_path: ./extensions/home # relative to the Vagrantfile


vagrant:
  plugins:
    - _id: "essential-hostmanager" # vagrant-hostmanager plugin
      enabled: true
      state: installed

    - _id: "v05-compat-gatling-rsync"
      _id_deprecated: "v05-compat-0"
      name: vagrant-gatling-rsync
      version: "" # empty means latest by default
      state: installed # uninstalled
      enabled: true
      config_key: gatling
      options:
        latency: 0.5
        time_format: "%%H:%%M:%%S"
        rsync_on_startup: true

    - _id: "v05-compat-rsync-back"
      _id_deprecated: "v05-compat-1"
      name: vagrant-rsync-back
      version: "" # empty means latest by default
      state: installed # uninstalled
      enabled: true

# teracy-dev v0.5 supports one node only, so let's follow that
nodes:
  - _id: "0"
    name: "%{node_name_prefix}.%{node_domain_affix}"
    vm:
      hostname: "%{node_hostname_prefix}.%{node_domain_affix}"
      networks:
        - _id: "v05-compat-public-network"
          _id_deprecated: "v05-compat-0"
          type: "public_network"
      synced_folders:
        - _id: "v05-compat-workspace"
          _id_deprecated: "v05-compat-0"
          type: rsync
          host: "./workspace"
          guest: "/home/vagrant/workspace"
          rsync__exclude:
            - ".git"
            - ".idea"
            - ".#*"
          create: true
        - _id: "v05-compat-docker" # should persist docker auth token after login success #170
          type: virtualbox
          host: "%{home_sync_path}/.docker"
          guest: "/home/vagrant/.docker"
          mount_options:
            - dmode=775
            - fmode=755
          create: true

    provisioners:
      - _id: "v05-compat-chef"
        _id_deprecated: 'v05-compat-0'
        name: teracy-dev-v05-compat
        version: 15.8.23
        type: chef_solo
        log_level: info
        enabled: true
        arguments: "--chef-license accept"
        # Please update right cookbooks, role, nodes, data_bags and run_list path in you entry config
        cookbooks_path:
          - "%{teracy-dev-v05-compat-path}/provisioners/chef_solo/vendor-cookbooks"
          - "%{teracy-dev-v05-compat-path}/provisioners/chef_solo/main-cookbooks"
        roles_path: "%{teracy-dev-v05-compat-path}/provisioners/chef_solo/roles"
        nodes_path: "%{teracy-dev-v05-compat-path}/provisioners/chef_solo/nodes"
        data_bags_path: "%{teracy-dev-v05-compat-path}/provisioners/chef_solo/data_bags"
        run_list:
          - vim
          - teracy-dev
        json:
          # we mix teracy-dev config along with vender-cookbooks config, hopefully this is better than
          # separated as we did before, this is for advanded users only
          docker:
            enabled: true
            version: '' # use this to install a specific docker version, default: ""
            # used along with the version key, this is default for Ubuntu
            package_options: "--force-yes -o Dpkg::Options::='--force-confold' -o Dpkg::Options::='--force-all'"
            repo: main # one of main, test, experimental, default: "main"
            members:
              - vagrant # to append this member to "docker" group
            action: create # one of create, delete. Default: create
          docker_registry:
            force: false # set true to force re-login with all the defined entries, default: false (login once)
            entries: []
            # example:
            # entries:
            #   - host: https://index.docker.io/v1/
            #     username: ""
            #     password: ""
            #   - host: registry.gitlab.com
            #     username: ""
            #     password: ""
          docker_compose:
            version: '' # more: https://github.com/docker/compose/releases/
            enabled: true # "docker" must be enabled to get this
          docker_machine:
            enabled: false
            release: v0.8.2 # more: https://github.com/docker/machine/releases/
          teracy-dev:
            directories:
              - _id: "v05-compat-workspace"
                _id_deprecated: 'v05-compat-0'
                path: "/home/vagrant/workspace"
                owner: vagrant
                group: vagrant
                mode: '0775'
                action: create # one of create, delete, nothing. Default: create
                # See more: https://docs.chef.io/resource_directory.html
            aliases:
              - _id: "v05-compat-ws"
                _id_deprecated: 'v05-compat-0'
                name: ws
                command: cd ~/workspace
                action: add
              - _id: "v05-compat-ctop"
                _id_deprecated: 'v05-compat-1'
                name: ctop # `$ ctop` for top-like interface for container metrics, see: https://github.com/bcicen/ctop
                command: docker run -ti --name ctop --rm -v /var/run/docker.sock:/var/run/docker.sock
                  quay.io/vektorlab/ctop:latest
                action: add
              - _id: "v05-compat-http"
                _id_deprecated: 'v05-compat-2'
                name: http # `$ http` to make http requests, how to use: https://github.com/teracyhq/httpie-jwt-auth
                command: docker container run -it --rm --net=host teracy/httpie-jwt-auth:latest-alpine
                action: add
              - _id: "v05-compat-https"
                _id_deprecated: 'v05-compat-3'
                name: https # shortcut for making https requests
                command: http --default-scheme=https
                action: add
            env_vars:
              - _id: "v05-compat-editor"
                _id_deprecated: 'v05-compat-0'
                key: EDITOR
                value: vim
                action: add # one of add, remove. Default: add
                # See more: https://github.com/customink-webops/magic_shell/blob/master/resources/environment.rb
            inotify:
              max_user_watches: 524288 # see: https://github.com/teracyhq/dev/issues/208, set value = 0 to unset this setting
            proxy:
              enabled: true
              certs:
                enabled: true
                sources:
                  - nginx/certs/default.crt
                  - nginx/certs/default.key
                destination: "/etc/nginx/certs"
                owner: vagrant
                group: vagrant
                mode: '0644'
              container:
                enabled: false
                name: nginx-proxy
                repo: jwilder/nginx-proxy
                tag: alpine
                volumes:
                  - "/var/run/docker.sock:/tmp/docker.sock:ro"
                  - "/etc/nginx/certs:/etc/nginx/certs"
                restart_policy: always
                port:
                  - 80:80
                  - 443:443
