version: '3'

services:

  lint:
    image: teracy/chefdk
    working_dir: /opt/app
    command: sh -c "cookstyle main-cookbooks"
    volumes:
      - .:/opt/app

  install:
    image: teracy/chefdk
    working_dir: /opt/app
    command: sh run-dev.sh
    volumes:
      - .:/opt/app
